import type { Dictionary } from '@/i18n/I18nProvider';

/** Strings for every chrome element on the patient chart. */
export const detailDict = {
  // Banner + actions
  notFoundTitle: { en: 'Patient not found', ko: '환자를 찾을 수 없습니다' },
  notFoundDesc: {
    en: 'This chart may have been discharged or the link is no longer valid.',
    ko: '해당 차트가 퇴원 처리되었거나 링크가 더 이상 유효하지 않습니다.',
  },
  backToRoster: { en: 'Back to roster', ko: '환자 목록으로' },
  startVoiceRound: { en: 'Start Voice Round', ko: '음성 회진 시작' },
  exportPdf: { en: 'Export PDF', ko: 'PDF 내보내기' },
  mrn: { en: 'MRN', ko: '등록번호' },
  ageSex: { en: 'Age / Sex', ko: '나이 / 성별' },
  location: { en: 'Location', ko: '위치' },
  attending: { en: 'Attending', ko: '주치의' },
  primaryNurse: { en: 'Primary Nurse', ko: '담당 간호사' },
  los: { en: 'Length of Stay', ko: '재원 기간' },
  losDays: { en: 'days', ko: '일' },
  code: { en: 'Code', ko: '심폐소생술' },
  isolation: { en: 'Isolation', ko: '격리' },
  diet: { en: 'Diet', ko: '식이' },
  mobility: { en: 'Mobility', ko: '기동' },
  bloodType: { en: 'Blood Type', ko: '혈액형' },
  bmi: { en: 'BMI', ko: '체질량지수' },
  admitted: { en: 'Admitted', ko: '입원일' },
  allergies: { en: 'Allergies', ko: '알레르기' },
  nkda: { en: 'NKDA — No Known Drug Allergies', ko: 'NKDA — 알려진 약물 알레르기 없음' },
  male: { en: 'Male', ko: '남' },
  female: { en: 'Female', ko: '여' },

  // Tabs
  tabOverview: { en: 'Overview', ko: '개요' },
  tabVitals: { en: 'Vitals', ko: '활력징후' },
  tabLabs: { en: 'Labs', ko: '검사' },
  tabMeds: { en: 'Medications', ko: '투약' },
  tabNanda: { en: 'Nursing Dx', ko: '간호진단' },
  tabAssessment: { en: 'Assessment', ko: '사정' },
  tabCarePlan: { en: 'Care Plan', ko: '간호계획' },
  tabRecords: { en: 'Records', ko: '간호기록' },

  // Overview
  latestVitals: { en: 'Latest Vital Signs', ko: '최근 활력징후' },
  measuredAt: { en: 'Measured', ko: '측정' },
  newsScore: { en: 'NEWS-style Score', ko: 'NEWS 점수' },
  newsLow: { en: 'Low clinical risk', ko: '낮은 임상 위험' },
  newsMedium: { en: 'Medium — increase monitoring', ko: '중등도 — 모니터링 강화' },
  newsHigh: { en: 'High — urgent review', ko: '높음 — 긴급 평가 필요' },
  map: { en: 'MAP', ko: '평균동맥압' },
  problemList: { en: 'Problem List', ko: '문제 목록' },
  primaryDx: { en: 'Primary', ko: '주진단' },
  secondaryDx: { en: 'Secondary', ko: '부진단' },
  onset: { en: 'Onset', ko: '발병' },
  activeNanda: { en: 'Active Nursing Diagnoses', ko: '활성 간호진단' },
  snapshot: { en: 'Clinical Snapshot', ko: '임상 요약' },
  intakeOutput: { en: 'Intake / Output (last record)', ko: '섭취/배설 (최근 기록)' },
  intake: { en: 'Intake', ko: '섭취량' },
  output: { en: 'Output', ko: '배설량' },
  balance: { en: 'Balance', ko: '균형' },

  // Vitals
  vitalsTrend: { en: 'Vital Sign Trends', ko: '활력징후 추이' },
  vitalsSubtitle: {
    en: 'Last 16 samples · 2-hour intervals',
    ko: '최근 16회 측정 · 2시간 간격',
  },
  latest: { en: 'Latest', ko: '최근' },
  bloodPressure: { en: 'Blood Pressure', ko: '혈압' },
  systolic: { en: 'Systolic', ko: '수축기' },
  diastolic: { en: 'Diastolic', ko: '이완기' },
  refBand: { en: 'Reference band', ko: '정상 범위' },

  // Labs
  labResults: { en: 'Laboratory Results', ko: '검사 결과' },
  collected: { en: 'Collected', ko: '채취' },
  analyte: { en: 'Analyte', ko: '검사 항목' },
  result: { en: 'Result', ko: '결과' },
  reference: { en: 'Reference', ko: '참고치' },
  flag: { en: 'Flag', ko: '판정' },
  abnormalCount: { en: 'abnormal', ko: '이상' },

  // Medications
  activeMeds: { en: 'Active Medication Orders', ko: '활성 처방' },
  medication: { en: 'Medication', ko: '약물' },
  dose: { en: 'Dose', ko: '용량' },
  route: { en: 'Route', ko: '경로' },
  frequency: { en: 'Frequency', ko: '투여 빈도' },
  indication: { en: 'Indication', ko: '적응증' },
  status: { en: 'Status', ko: '상태' },
  highAlert: { en: 'High-alert medication', ko: '고위험 약물' },
  nextDue: { en: 'Next due', ko: '다음 투여' },
  marTitle: { en: 'Medication Administration Record', ko: '투약 기록 (MAR)' },
  scheduled: { en: 'Scheduled', ko: '예정' },
  by: { en: 'by', ko: '간호사' },

  // NANDA
  nandaTitle: { en: 'NANDA-I Nursing Diagnoses', ko: 'NANDA-I 간호진단' },
  nandaSubtitle: {
    en: 'Each diagnosis links to a NOC outcome and NIC interventions',
    ko: '각 진단은 NOC 결과 및 NIC 중재와 연계됩니다',
  },
  domain: { en: 'Domain', ko: '영역' },
  definingChars: { en: 'Defining Characteristics', ko: '특성 정의' },
  relatedFactors: { en: 'Related Factors', ko: '관련 요인' },
  nocOutcome: { en: 'NOC Outcome', ko: 'NOC 결과' },
  nicInterventions: { en: 'NIC Interventions', ko: 'NIC 중재' },
  identified: { en: 'Identified', ko: '진단일' },

  // Assessment
  assessmentTitle: { en: 'Standardized Assessment Scales', ko: '표준 사정 도구' },
  braden: { en: 'Braden Scale', ko: '브레이든 척도' },
  bradenSub: { en: 'Pressure injury risk', ko: '욕창 위험' },
  morse: { en: 'Morse Fall Scale', ko: '모스 낙상 척도' },
  morseSub: { en: 'Fall risk', ko: '낙상 위험' },
  gcs: { en: 'Glasgow Coma Scale', ko: '글래스고 혼수 척도' },
  gcsSub: { en: 'Level of consciousness', ko: '의식 수준' },
  painScale: { en: 'Pain (NRS)', ko: '통증 (NRS)' },
  painSub: { en: 'Numeric rating 0–10', ko: '0–10 숫자 평가' },
  riskLabel: { en: 'Risk', ko: '위험도' },
  eye: { en: 'Eye', ko: '눈' },
  verbal: { en: 'Verbal', ko: '언어' },
  motor: { en: 'Motor', ko: '운동' },
  total: { en: 'Total', ko: '총점' },
  noPain: { en: 'No pain', ko: '통증 없음' },
  mildPain: { en: 'Mild', ko: '경증' },
  moderatePain: { en: 'Moderate', ko: '중등도' },
  severePain: { en: 'Severe', ko: '중증' },

  // Care plan
  carePlanTitle: { en: 'Care Plan', ko: '간호계획' },
  carePlanSubtitle: {
    en: 'Toggle a task to mark it complete',
    ko: '항목을 선택하여 완료로 표시',
  },
  due: { en: 'Due', ko: '예정' },
  completedTasks: { en: 'completed', ko: '완료' },
  taskCompleted: { en: 'Completed', ko: '완료됨' },
  taskPending: { en: 'Pending', ko: '대기' },
  taskInProgress: { en: 'In progress', ko: '진행 중' },

  // Records
  recordsTitle: { en: 'Documentation', ko: '간호기록' },
  recordsSubtitle: { en: 'Voice rounds and nursing notes', ko: '음성 회진 및 간호 노트' },
  signed: { en: 'Signed', ko: '서명됨' },
  unsigned: { en: 'Unsigned', ko: '미서명' },
  recRounding: { en: 'Voice Round', ko: '음성 회진' },
  recSOAP: { en: 'SOAP Note', ko: 'SOAP 기록' },
  recNarrative: { en: 'Narrative', ko: '서술 기록' },
  recAssessment: { en: 'Assessment', ko: '사정 기록' },
  noRecords: { en: 'No documentation yet', ko: '아직 기록이 없습니다' },
  noRecordsDesc: {
    en: 'Completed voice rounds and notes for this patient will appear here.',
    ko: '이 환자에 대한 음성 회진 및 노트가 여기에 표시됩니다.',
  },
  subjective: { en: 'Subjective', ko: '주관적' },
  objective: { en: 'Objective', ko: '객관적' },
  assessmentSoap: { en: 'Assessment', ko: '사정' },
  plan: { en: 'Plan', ko: '계획' },
  duration: { en: 'Duration', ko: '소요 시간' },
  engine: { en: 'Engine', ko: '엔진' },
  confidence: { en: 'Confidence', ko: '인식 정확도' },
  question: { en: 'Question', ko: '질문' },
  response: { en: 'Response', ko: '응답' },
  structuredEntry: { en: 'Charted as', ko: '기록 내용' },
} satisfies Dictionary;
